[main]
log_level = "debug"
port = 9000
log_dir = "./logs"


[db]
host = "172.168.1.150"
port = 3306
user = "root"
password = "aixocm"
db = "raytheon"
charset = "utf8"
max_open_conns = 2000
max_idle_conns = 1000

[redis]
host = "172.168.1.150"
port = 6379
password = ""
db = 7

# todo:
[ldap]
enable = false
addr = "39.105.81.109"
port = 389
base_dn = "dc=yongqianbao,dc=com"
bind_dn = "cn=Manager,dc=yongqianbao,dc=com"
bind_pass = "6MRuns"
auth_filter = ""
attr_filter = ""
tls = false
start_tls = false


